apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: helm-ftp
  region: eu-west-3

nodeGroups:
  - name: node-group-1
    instanceType: t2.micro
    desiredCapacity: 3
    minSize: 2
    maxSize: 4