apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0c1049ab76f351f10
  directoryPerms: "700"
mountOptions:
  - tls
reclaimPolicy: Retain
volumeBindingMode: Immediate
