replicaCount: 1

image:
  repository: delfer/alpine-ftp-server
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb" 
  ports:
    - name: ftp
      port: 21
      targetPort: 21
    - name: passive
      port: 21000
      targetPort: 21000
    - name: passive-last
      port: 21010
      targetPort: 21010

environment:
  USERS: jeanadmin|12345jean
  ADDRESS: http://ftp.jeanops.net


#persistence:
#  enabled: true
#  accessModes:
#    - ReadWriteMany
#  size: 5Gi
#  storageClassName: "efs-sc"
#  existingClaim: "efs-pvc"
