apiVersion: v1
kind: Service
metadata:
  name: {{ include "ftp-server.fullname" . }}
  labels:
    {{- include "ftp-server.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      {{- if eq "LoadBalancer" "NodePort" }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "ftp-server.selectorLabels" . | nindent 4 }}
